name: coh3_modding
channels:
  - anaconda
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - freetype=2.12.1
  - jpeg=9e
  - lerc=3.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libpng=1.6.37
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - openssl=1.1.1t
  - pillow=9.3.0
  - pip=23.0.1
  - python=3.10.9
  - setuptools=65.6.3
  - sqlite=3.41.1
  - tk=8.6.12
  - tzdata=2022g
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.38.4
  - wincertstore=0.2
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - texture2ddecoder==1.0.4